### ISSUE TITLE
Cosi - Just Fix Segmentation fault Error

### ISSUE THREAD

**Issue by emma-eva** [gardhr/matrix#1]
I am interest your cosi repository. I know repository has been archived but i like it to use. I am getting 4 warning `'long'` to `double`, `'long long'` to `double`, `'unsigned long'` to `double`,  and `'unsigned long long'` to `double`.

Main error is that: After call `./cosi` i am getting this error
```
Segmentation fault
````
Its the main problem, i cant run cosi. Plz help me to just fix it, i want to run it. I will be very happy :) Advance thanks.

**Comment by gardhr** [comment]
Hard to say. The project was based on a much older compiler tool chain too. In any case none of that is related to this repository.

**Comment by emma-eva** [comment]
Plz remember which version comiler toolchain did you used,  also i cant create issues on yoir cosi repo, havent issue button.

**Comment by emma-eva** [comment]
https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

did you used above toolchain?
