### ISSUE TITLE
Which IDE did you used on Cosi?

### ISSUE THREAD

**Issue by emma-eva** [gardhr/matrix#2]
Plz give me guide line, which IDE and what extension did you used? Plz help me to use it. Advance thanks.

I cant create issue on cosi, bcz new issue not available. So creating here.

**Comment by emma-eva** [comment]
if you want i will pay you, just fix cosi

**Comment by emma-eva** [comment]
Whatsapp: +14044822340

**Comment by gardhr** [comment]
Unfortunately, no further feature requests are being accepted at this time for that repository. (NOTE: Your comment containing personal contact information has been deleted.)
